name: DEPLOY

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: deploy
    environment:
      name: main
    runs-on: ubuntu-latest
    env:
      CDK_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
    
      - name: Install CDK dependencies
        run: |
          cd deploy && npm install

      - name: CDK Deploy
        run: |
          cd deploy && npm run cdk deploy -- --all --require-approval never

      - name: Deploy Next.js app to EC2
        run: |
          # Get instance ID from SSM Parameter 
          INSTANCE_ID=$(aws ssm get-parameter --name "/webapp/webapp-ec2-instance-id" --query "Parameter.Value" --output text)
          echo "Retrieved instance ID: $INSTANCE_ID"
          
          # Build the Next.js app
          echo "Current directory: $(pwd)"
          cd src/webapp
          echo "Changed to src/webapp directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          # Install dependencies
          echo "Installing dependencies..."
          npm ci
          
          # Build the app
          echo "Building Next.js app..."
          npm run build
          
          echo "Build completed. Directory contents:"
          ls -la
          
          # Check for .next or out directory
          echo "Build output directories:"
          ls -la .next || echo ".next directory not found"
          ls -la out || echo "out directory not found"
          
          # Create a deployment package - check for static export first
          echo "Creating deployment package..."
          if [ -d "out" ]; then
            # Static export case
            cd out
            echo "Using out directory (static export): $(pwd)"
            zip -r ../../../webapp.zip .
          elif [ -d ".next" ]; then
            # Server-side rendering case - need to include more files
            echo "Using .next directory (SSR): $(pwd)"
            # For SSR, we need the .next folder, package.json, and node_modules
            zip -r ../../../webapp.zip .next package.json package-lock.json next.config.js public
            # For a production deployment, you might want to do a npm ci --production 
            # and include node_modules, but that makes the zip very large
          else
            echo "ERROR: Neither .next nor out directory found. Check if this is a Next.js app and the build succeeded."
            exit 1
          fi
          
          echo "Zip file created at ../../../webapp.zip"
          
          # Create a unique bucket name using instance ID
          BUCKET_NAME="temp-webapp-deployment-$(echo $INSTANCE_ID | tr -d '-')"
          echo "Using S3 bucket: $BUCKET_NAME"
          
          # Use AWS S3 as an intermediary for the file transfer
          echo "Creating/using S3 bucket..."
          aws s3 mb s3://$BUCKET_NAME --region ${{ vars.AWS_DEFAULT_REGION }} || true
          
          echo "Uploading webapp.zip to S3..."
          cd ../../../  # Return to root directory
          aws s3 cp webapp.zip s3://$BUCKET_NAME/webapp.zip
          
          # Use SSM to download and deploy the app
          echo "Deploying app to EC2 via SSM..."
          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --parameters commands=[
              "aws s3 cp s3://$BUCKET